version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: 'logs/app.log'  
    maxBytes: 5242880  # 5 MB 
    backupCount: 3  # Keeps 3 files on backup
loggers:
  root:
    level: DEBUG
    handlers: [stdout, file_handler]

